### PR TITLE
Data Structures Proposal -> Linked List

### PR DESCRIPTION
**Pull request by Knevari**

### CODE REVIEW

**Comment by Knevari** [comment]
If you can take some time, could you explain to me why my linked list implementation only takes 67.85% code coverage? And why should I look forward to improving it?

**Comment by Knevari** [comment]
Wrote a lot more tests to increase the code coverage

**Comment by nas5w** [comment]
There is currently an implementation of Linear Search in the repository. Your implementation is different--it appears to return multiple indexes if there are multiple matches. That doesn't seem to be correct from what I find on the internet. Where did your version (that returns multiple indexes) come from?

**Comment by Knevari** [comment]
Sorry, but this Pull Request is about the Linked List data structure. My another PR that presents linear search algorithm is based on the code of another repo called javascript-algorithms, it returns the indexes of the elements found in the array, but I think it was my bad since I didn't see the previous linear search pull request.

**Comment by Knevari** [comment]
It appears that some of my commits from the previous Pull Request got here in this PR too, can I make another Pull Request sending just the changes related to the linked list data structure?

**Comment by nas5w** [comment]
Sure, that works. If possible, rebase onto the current master of this repository to make it a clean merge!

**Comment by Knevari** [comment]
I improved the readability of some tests and the total coverage in the last commit, removed my implementation of linear search and made a clean merge by cloning the repo master branch again.

**Pull request merged**
